#include <cstdlib>

#define FAILED_CREATE_STACK 11
#define FAILED_CREATE_STACK_DATA 12

#define STACK_WASNT_RESEIVED_SPUSH 21
#define STACK_WASNT_RESEIVED_SPOP 22
#define STACK_NOT_FOUND_SDESTROY 23

#define REACHES_THE_MIN 41
