#include <cstdlib>

#define ST_DATA_NULL 11
#define FAILED_CREATE_STACK_DATA 12
#define STACK_WASNT_CREATED 13

#define STACK_IS_EMPTY_SPOP 22
#define FAILED_TO_DESTROY_STACK 23

#define ST_SIZE_IS_NOT_PLUS 51
#define STACK_WAS_CREATED_ALREADY 52

#define STACK_NOT_FOUND 61

#define ST_HASH_WAS_CHANGED 71
#define ST_DATA_HASH_WAS_CHANGED 72

#define ST_CANARY1_WAS_CHANGED 73
#define ST_CANARY2_WAS_CHANGED 74
#define DATA_CANARY1_WAS_CHANGED 751
#define DATA_CANARY2_WAS_CHANGED 752
